### ISSUE TITLE
请问一个问题

### ISSUE THREAD

**Issue by Smile-shirley** [intersun/PKD-for-BERT-Model-Compression#10]
代码中有一个--teacher_prediction，这个哪来的？是在训练teacher模型中保存下来的？为什么没看到？

**Comment by Yu-Fangxu** [comment]
同问，我也卡在这里，找不到文件

**Comment by 1125690278** [comment]
> 代码中有一个--teacher_prediction，这个哪来的？是在训练teacher模型中保存下来的？为什么没看到？

Traceback (most recent call last):
  File "run_glue_benchmark.py", line 110, in <module>
    assert len(encoder_file) == 1 and len(cls_file) == 1, f'encoder/cls file err                        or: {encoder_file}, {cls_file}'
AssertionError: encoder/cls file error: [], []
请问运行run_glue_benchmark.py时为啥会有这个错误

**Comment by winston52** [comment]
运行  run_glue_benchmark.py 可以得到对应的文件

设置output_all_layers = True/False 可以得到不同蒸馏方法对应的两个文件

**Comment by ZHEGG** [comment]
> > 代码中有一个--teacher_prediction，这个哪来的？是在训练teacher模型中保存下来的？为什么没看到？
> 
> Traceback (most recent call last): File "run_glue_benchmark.py", line 110, in assert len(encoder_file) == 1 and len(cls_file) == 1, f'encoder/cls file err or: {encoder_file}, {cls_file}' AssertionError: encoder/cls file error: [], [] 请问运行run_glue_benchmark.py时为啥会有这个错误

同问

**Comment by caowanxia123** [comment]
同样这个问题，请问怎么回事
