### ISSUE TITLE
RuntimeError: Function AddBackward0 returned an invalid gradient at index 1 - expected type torch.cuda.HalfTensor but got torch.cuda.FloatTensor

### ISSUE THREAD

**Issue by yg33717** [intersun/PKD-for-BERT-Model-Compression#6]
I Found  a bug,  when we set fp16=False,  and train RTE with kd.cls, got  this problem.   and the traceback is：
```
Traceback (most recent call last):
  File "NLI_KD_training.py", line 288, in <module>
    loss.backward()
  File "/home/vernon/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/vernon/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function AddBackward0 returned an invalid gradient at index 1 - expected type torch.cuda.HalfTensor but got torch.cuda.FloatTensor
```

**Comment by yg33717** [comment]
i solved this by rewriting the function patience_loss, we should consider the situation that fp16=False in pt loss:
```
def patience_loss(teacher_patience, student_patience, normalized_patience=False):
    # n_batch = teacher_patience.shape[0]
    if normalized_patience:
        teacher_patience = F.normalize(teacher_patience, p=2, dim=2)
        student_patience = F.normalize(student_patience, p=2, dim=2)
    # return F.mse_loss(teacher_patience.float(), student_patience.float()).half()   # before
    return F.mse_loss(teacher_patience.float(), student_patience.float())               # after
```

**Comment by intersun** [comment]
Thanks for your feedback and modification, much appreciated!

I always set fp16 as True so I didn't check what if we set fp16 as False.
